# Generated by Django 4.2.11 on 2024-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=100)),
                ("consumer_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("ssn", models.CharField(max_length=11)),
            ],
        ),
    ]
