# Generated by Django 4.2.11 on 2024-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
